Pre-Class Assignment 3 Matrix Scratch

Student: Nguyễn Tấn Tài

Problem 1: Matrix product is calculated manually

Given:

$$A = \begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix}, B = \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}$$

We denote matrix R as $$R = A \cdot B$$

Thus: $$R = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}$$

$a_{11} = -1 \times 0 + 2 \times 0 + 3 \times 2 = 6$

$a_{12} = -1 \times 2 + 2 \times 2 + 3 \times 9 = 29$

$a_{13} = -1 \times 1 + 2 \times -8 + 3 \times -1 = -20$

$a_{21} = 4 \times 0 + -5 \times 0 + 6 \times 2 = 12$

$a_{22} = 4 \times 2 + -5 \times 2 + 6 \times 9 = 52$

$a_{23} = 4 \times 1 + -5 \times -8 + 6 \times -1 = 38$

$a_{31} = 7 \times 0 + 8 \times 0 + -9 \times 2 = -18$

$a_{32} = 7 \times 2 + 8 \times 2 + -9 \times 9 = -51$

$a_{33} = 7 \times 1 + 8 \times -8 + -9 \times -1 = -48$

Therefore the product of matrices A and B is:

Thus: $$R = A \cdot B = \begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{bmatrix}$$

Problem 2: Calculation by NumPy function

In [3]:
import numpy as np

A = np.array([
            [-1, 2, 3], 
            [4, -5, 6], 
            [7, 8, -9]
            ])
B = np.array([
            [0, 2, 1], 
            [0, 2, -8], 
            [2, 9, -1]
            ])

print(np.dot(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Problem 3: Implementation of calculation of a certain element

In [4]:
result = np.zeros((3, 3))

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B[0])):
            result[i][j] += A[i][k] * B[k][j]

print(result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 4: Creating a function that performs matrix multiplication

In [5]:
def matrix_mul(A, B):
    result = np.zeros((len(A), len(B[0])))

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B[0])):
                result[i][j] += A[i][k] * B[k][j]

    return result

result = matrix_mul(A, B)
print(result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 5: Judge the input whose calculation is not defined

In [6]:
D = np.array([
            [-1, 2, 3],
            [4, -5, 6]
            ])

E = np.array([
            [-9, 8, 7],
            [6, -5, 4]
            ])

def matrix_mul(A, B):
    if (len(A) != len(B[0])):
        print("The number of columns in the first matrix must be equal to the number of rows in the second matrix")
        return

    result = np.zeros((len(A), len(B[0])))

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B[0])):
                result[i][j] += A[i][k] * B[k][j]

    return result

result = matrix_mul(D, E)
print(result)

The number of columns in the first matrix must be equal to the number of rows in the second matrix
None


Problem 6: Transposition

In [7]:
result = matrix_mul(D, E.T)
print(result)

[[ 25. -16.]
 [-76.  49.]]
